### ISSUE TITLE
Brunch getDependencies wrong arguments

### ISSUE THREAD

**Issue by samio80** [monokrome/jaded-brunch#20] opened 2016-04-04 09:34 UTC
Brunch calls like:

`return promisifyPlugin(2, compiler.getDependencies).call(compiler, data, path);`

but progeny calls like:
` => data, path, compiler`

Please modify to solve it: (JS version, CS version included in the patch)
```
var progenyDeps = progeny({
      rootPath:  ....
    });
    this.getDependencies = function(compiler, data, path){
      progenyDeps(data, path, compiler)
    }
```

**Comment by samio80** [comment] 2016-04-04 11:51
Fix in CS attached here It's also tested , can you please merge?

[fix-issue-https-github.com-monokrome-jaded-brunch-is.diff.zip](https://github.com/monokrome/jaded-brunch/files/202325/fix-issue-https-github.com-monokrome-jaded-brunch-is.diff.zip)

**Comment by monokrome** [comment] 2016-04-07 02:57
@samio80 Are you able to send this as a pull request?

**Comment by monokrome** [comment] 2016-04-11 06:22
@samio80 Does this look like what you're expecting? If so, I'll test that it's working:

https://github.com/monokrome/jaded-brunch/pull/21

**Comment by monokrome** [comment] 2016-04-11 06:23
@samio80 Thanks so much for reporting this! Does https://github.com/monokrome/jaded-brunch/pull/21 look like what you're expecting? If so, I'll test that it's working

**Comment by monokrome** [comment] 2016-04-12 20:22
@samio80 Closing this now, and we can work on it in #21 since you've confirmed that #21 is the ideal state. Feel free to reopen this issue if you feel like it should be open! Thanks again :)

**Closed by monokrome** 2016-04-12 20:22 UTC
